하루 길이 (틱): 24000
폭죽 사용시 내구도 감소량: 6
침대 파괴 주기 (일): 15
자석석 고장 주기 (일): 15
늑대 강화 주기 (일): 15
늑대 강화 배수: 1.5
팬텀 스폰 주기 (초): 360
팬텀 스폰 지연 (일): 1
팬텀 스폰 수: 2
몬스터 체력 배수: 1.2
몬스터 공격력 배수: 1.2
언데드 체력 배수: 1.4
언데드 공격력 배수: 1.4
위더스켈/블레이즈 체력 배수: 1.6
위더스켈/블레이즈 공격력 배수: 1.6

날짜: 0